### ISSUE TITLE
After Pasting inside addEventListener the code isn't running in the browser.

### ISSUE THREAD

**Issue by AmilMasic** [learn-co-curriculum/fewpjs-event-listening#7]
The code gives me feedback when I copy and paste it into the console, I get the message back. However, when copy and pasting it into the function in index.js inside the browser nothing happens. I tried the listed solution too and it didn't work. I commented out function addEventListener and it worked, but the tests failed due to not having addEventListener.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
